name: Pull Docker Image to keep it activated

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 */3 *'
    
jobs:
  
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USER }}
      DOCKERHUB_PASS: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: | 
        docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASS"
        sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
        sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
        docker pull fmalmeida/ngs-preprocess
