name: Pull Docker Image to keep it activated

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 */3 *'
    
jobs:
  
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: | 
      echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      sudo rm -rf /usr/local/lib/android
      sudo rm -rf /usr/share/dotnet
      docker pull fmalmeida/ngs-preprocess
